version: '3.7'

services:
  web:
    build: .
    volumes:
      - ./site:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=465798
      - MYSQL_DATABASE=db_transportadora
      - MYSQL_USER=joker
      - MYSQL_PASSWORD=465798
    ports:
      - 3306:3306
    security_opt:
      - seccomp=unconfined
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=465798